opt_in_rules:
  - implicit_return
  - let_var_whitespace
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - sorted_imports

analyzer_rules:
  - unused_import

file_length:
  warning: 800
  error: 1200

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 60
  error: 80 
